.circleci/config.yml
test/testNewrelic.js
test/testStatuspage.js

Tests are not running in CI yet.

test(ci): run tests in ci

---

.circleci/orbs/helix-post-deploy/orb.yml

Fix #10 by removing escaping from parameter doublequotes

fix(monitoring): monitoring setup fails (#10)

---

test/testOrbRelease.js

2 orb-release tests are failing.

test(orb): fix tests

---

.circleci/orbs/helix-post-deploy/orb.yml
src/newrelic/cli.js
src/newrelic/synthetics.js
test/fixtures/monitor_script.js
test/testNewrelic.js
test/testOrbRelease.js

feat(monitoring): ability to use custom script

---

README.md
src/newrelic/alerts.js
src/newrelic/cli.js
src/statuspage/cli.js
src/utils.js
test/testNewrelic.js
test/testStatuspage.js

feat(monitoring): add incubator mode

---

.circleci/orbs/helix-post-deploy/orb.yml

feat(monitoring): add incubator support to helix-post-deploy orb

---

package-lock.json
package.json

chore(deps): fix vulnerabilities

---

src/newrelic/monitor_script.js

fix #48
Please ensure your pull request adheres to the following guidelines:
Thanks for contributing!

fix(monitor_script): guard against runtime errors

---

src/newrelic/monitor_script.js

fix(monitoring): relax if activation result cannot be retrieved

---

.circleci/config.yml
.circleci/orbs/helix-post-deploy/orb.yml
README.md
package.json
src/newrelic/cli.js
src/newrelic/synthetics.js
test/testNewrelic.js

feat(monitoring): ability to create scripted browser monitors

---

src/orb-release/cli.js

Improved orb release script to make sure orbs get released from CircleCI if source changed.

fix(ci): orb release can fail [skip ci]

---

.circleci/orbs/helix-post-deploy/orb.yml
README.md
src/newrelic/alerts.js
src/newrelic/cli.js
test/testNewrelic.js

feat(monitoring): make email optional

---

src/newrelic/synthetics.js

fix(monitoring): omit monitor type during update

---

package-lock.json

`npm audit fix` plus some manual `minimist` upgrades

chore(deps): fix vulnerable dependencies

---

.circleci/orbs/helix-post-deploy/orb.yml

feat(monitoring): use major action version

---

.circleci/orbs/helix-post-deploy/orb.yml
README.md
src/newrelic/cli.js
src/newrelic/synthetics.js
test/testNewrelic.js

feat(monitoring): optional monitor locations and frequency

---

src/newrelic/monitor_script.js

fix(montoring): ensure activation record is always persisted

---

.circleci/config.yml
README.md

feat: rename default branch from "master" to "main"

---

package-lock.json

chore: patch vulnerable dependencies

---

.circleci/orbs/helix-post-deploy/orb.yml

feat(orb): install CLI if not already installed

---

.circleci/orbs/helix-post-deploy/orb.yml
README.md
src/newrelic/alerts.js
src/newrelic/cli.js
src/newrelic/synthetics.js
src/statuspage/cli.js
test/AbstractAPI.js
test/newrelic/NewRelicAPI.js
test/statuspage/StatuspageAPI.js
test/testNewrelic.js
test/testStatuspage.js
test/utils.js

Fix #149 
BREAKING CHANGE: API change in newrelic CLI
from
```
newrelic setup <url> <email>
```
to
```
newrelic setup --url <url> --email <email>
```

feat(monitoring): aws support

---

.circleci/config.yml
package-lock.json
package.json
src/newrelic/alerts.js
src/newrelic/synthetics.js
src/statuspage/cli.js

Please ensure your pull request adheres to the following guidelines:
Thanks for contributing!

build(deps): update helix-fetch

---

.circleci/orbs/helix-post-deploy/orb.yml

fix(monitoring): script error (#155)

---

.circleci/orbs/helix-post-deploy/orb.yml

Broken script

---

.circleci/orbs/helix-post-deploy/orb.yml

fix(monitoring): aws monitoring always pointing to word2md/v2

---

.circleci/orbs/helix-post-deploy/orb.yml

Regression from https://github.com/adobe/helix-ops/pull/204

fix(monitoring): missing default values make parameters mandatory

---

src/newrelic/monitor_script.js

Improved error handling for failed requests as well as invalid JSON responses (e.g. login screen with status 200 from Google Cloud).

chore: error handling

---

package-lock.json
package.json
src/newrelic/alerts.js
src/newrelic/synthetics.js
src/statuspage/cli.js

Please ensure your pull request adheres to the following guidelines:
Thanks for contributing!

fix: @adobe/helix-fetch -> @adobe/fetch
